/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    songs: Song;
    languages: Language;
    genres: Genre;
    audiences: Audience;
    themes: Theme;
    'track-types': TrackType;
    'difficulty-levels': DifficultyLevel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    songs: SongsSelect<false> | SongsSelect<true>;
    languages: LanguagesSelect<false> | LanguagesSelect<true>;
    genres: GenresSelect<false> | GenresSelect<true>;
    audiences: AudiencesSelect<false> | AudiencesSelect<true>;
    themes: ThemesSelect<false> | ThemesSelect<true>;
    'track-types': TrackTypesSelect<false> | TrackTypesSelect<true>;
    'difficulty-levels': DifficultyLevelsSelect<false> | DifficultyLevelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs".
 */
export interface Song {
  id: number;
  title: string;
  /**
   * Auto-generated from title on create, but editable after
   */
  slug?: string | null;
  /**
   * Select a template image or upload a custom thumbnail
   */
  thumbnailPublicId?: string | null;
  countries?:
    | (
        | 'Afghanistan'
        | 'Afrique du Sud'
        | 'Albanie'
        | 'Algérie'
        | 'Allemagne'
        | 'Andorre'
        | 'Angola'
        | 'Antigua-et-Barbuda'
        | 'Arabie saoudite'
        | 'Argentine'
        | 'Arménie'
        | 'Australie'
        | 'Autriche'
        | 'Azerbaïdjan'
        | 'Bahamas'
        | 'Bahreïn'
        | 'Bangladesh'
        | 'Barbade'
        | 'Belgique'
        | 'Belize'
        | 'Bénin'
        | 'Bhoutan'
        | 'Biélorussie'
        | 'Birmanie'
        | 'Bolivie'
        | 'Bosnie-Herzégovine'
        | 'Botswana'
        | 'Brésil'
        | 'Brunei'
        | 'Bulgarie'
        | 'Burkina Faso'
        | 'Burundi'
        | 'Cambodge'
        | 'Cameroun'
        | 'Canada'
        | 'Cap-Vert'
        | 'Centrafrique'
        | 'Chili'
        | 'Chine'
        | 'Chypre'
        | 'Colombie'
        | 'Comores'
        | 'Congo'
        | 'Corée du Nord'
        | 'Corée du Sud'
        | 'Costa Rica'
        | "Côte d'Ivoire"
        | 'Croatie'
        | 'Cuba'
        | 'Danemark'
        | 'Djibouti'
        | 'Dominique'
        | 'Égypte'
        | 'Émirats arabes unis'
        | 'Équateur'
        | 'Érythrée'
        | 'Espagne'
        | 'Estonie'
        | 'Eswatini'
        | 'États-Unis'
        | 'Éthiopie'
        | 'Fidji'
        | 'Finlande'
        | 'France'
        | 'Gabon'
        | 'Gambie'
        | 'Géorgie'
        | 'Ghana'
        | 'Grèce'
        | 'Grenade'
        | 'Guatemala'
        | 'Guinée'
        | 'Guinée équatoriale'
        | 'Guinée-Bissau'
        | 'Guyana'
        | 'Haïti'
        | 'Honduras'
        | 'Hongrie'
        | 'Inde'
        | 'Indonésie'
        | 'Irak'
        | 'Iran'
        | 'Irlande'
        | 'Islande'
        | 'Israël'
        | 'Italie'
        | 'Jamaïque'
        | 'Japon'
        | 'Jordanie'
        | 'Kazakhstan'
        | 'Kenya'
        | 'Kirghizistan'
        | 'Kiribati'
        | 'Kosovo'
        | 'Koweït'
        | 'Laos'
        | 'Lesotho'
        | 'Lettonie'
        | 'Liban'
        | 'Liberia'
        | 'Libye'
        | 'Liechtenstein'
        | 'Lituanie'
        | 'Luxembourg'
        | 'Macédoine du Nord'
        | 'Madagascar'
        | 'Malaisie'
        | 'Malawi'
        | 'Maldives'
        | 'Mali'
        | 'Malte'
        | 'Maroc'
        | 'Marshall'
        | 'Maurice'
        | 'Mauritanie'
        | 'Mexique'
        | 'Micronésie'
        | 'Moldavie'
        | 'Monaco'
        | 'Mongolie'
        | 'Monténégro'
        | 'Mozambique'
        | 'Namibie'
        | 'Nauru'
        | 'Népal'
        | 'Nicaragua'
        | 'Niger'
        | 'Nigeria'
        | 'Norvège'
        | 'Nouvelle-Zélande'
        | 'Oman'
        | 'Ouganda'
        | 'Ouzbékistan'
        | 'Pakistan'
        | 'Palaos'
        | 'Palestine'
        | 'Panama'
        | 'Papouasie-Nouvelle-Guinée'
        | 'Paraguay'
        | 'Pays-Bas'
        | 'Pérou'
        | 'Philippines'
        | 'Pologne'
        | 'Porto Rico'
        | 'Portugal'
        | 'Qatar'
        | 'République démocratique du Congo'
        | 'République dominicaine'
        | 'Roumanie'
        | 'Royaume-Uni'
        | 'Russie'
        | 'Rwanda'
        | 'Sahara occidental'
        | 'Saint-Kitts-et-Nevis'
        | 'Saint-Marin'
        | 'Saint-Vincent-et-les-Grenadines'
        | 'Sainte-Lucie'
        | 'Salomon'
        | 'Salvador'
        | 'Samoa'
        | 'Sao Tomé-et-Príncipe'
        | 'Sénégal'
        | 'Serbie'
        | 'Seychelles'
        | 'Sierra Leone'
        | 'Singapour'
        | 'Slovaquie'
        | 'Slovénie'
        | 'Somalie'
        | 'Soudan'
        | 'Soudan du Sud'
        | 'Sri Lanka'
        | 'Suède'
        | 'Suisse'
        | 'Suriname'
        | 'Syrie'
        | 'Tadjikistan'
        | 'Taïwan'
        | 'Tanzanie'
        | 'Tchad'
        | 'Tchéquie'
        | 'Thaïlande'
        | 'Timor oriental'
        | 'Togo'
        | 'Tonga'
        | 'Trinité-et-Tobago'
        | 'Tunisie'
        | 'Turkménistan'
        | 'Turquie'
        | 'Tuvalu'
        | 'Ukraine'
        | 'Uruguay'
        | 'Vanuatu'
        | 'Vatican'
        | 'Venezuela'
        | 'Viêt Nam'
        | 'Yémen'
        | 'Zambie'
        | 'Zimbabwe'
      )[]
    | null;
  languages?: (number | Language)[] | null;
  genres?: (number | Genre)[] | null;
  audiences?: (number | Audience)[] | null;
  themes?: (number | Theme)[] | null;
  difficulty?: (number | null) | DifficultyLevel;
  /**
   * Add lyrics in different languages. Each lyric can have its own translations.
   */
  lyrics?:
    | {
        language: number | Language;
        /**
         * The lyrics text in this language
         */
        text: string;
        /**
         * Translations specific to this lyric version
         */
        translations?:
          | {
              language: number | Language;
              /**
               * The translation text
               */
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Add score PDFs
   */
  scores?:
    | {
        /**
         * Upload score PDF
         */
        pdfPublicId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Add history document PDFs in different languages
   */
  historyDocuments?:
    | {
        language: number | Language;
        /**
         * Upload history document PDF
         */
        pdfPublicId: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Add audio tracks with versions
   */
  audioTracks?:
    | {
        trackType: number | TrackType;
        /**
         * Add different versions of this track
         */
        versions?:
          | {
              /**
               * Unique identifier for this version (e.g., v1, v2)
               */
              versionId: string;
              /**
               * Display name for this version
               */
              name: string;
              /**
               * Upload audio file
               */
              audioPublicId: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages".
 */
export interface Language {
  id: number;
  name: string;
  /**
   * English name (e.g., "French" for "Français")
   */
  nameEn?: string | null;
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres".
 */
export interface Genre {
  id: number;
  name: string;
  /**
   * English translation of the genre name
   */
  nameEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audiences".
 */
export interface Audience {
  id: number;
  name: string;
  /**
   * English translation of the audience name
   */
  nameEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes".
 */
export interface Theme {
  id: number;
  name: string;
  /**
   * English translation of the theme name
   */
  nameEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulty-levels".
 */
export interface DifficultyLevel {
  id: number;
  name: string;
  /**
   * English translation of the difficulty level name
   */
  nameEn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "track-types".
 */
export interface TrackType {
  id: number;
  /**
   * Display name in French (e.g., "Groupe", "Violon")
   */
  name: string;
  /**
   * Display name in English (e.g., "Full Band", "Violin")
   */
  nameEn?: string | null;
  /**
   * URL-friendly identifier (e.g., "groupe", "violon")
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'songs';
        value: number | Song;
      } | null)
    | ({
        relationTo: 'languages';
        value: number | Language;
      } | null)
    | ({
        relationTo: 'genres';
        value: number | Genre;
      } | null)
    | ({
        relationTo: 'audiences';
        value: number | Audience;
      } | null)
    | ({
        relationTo: 'themes';
        value: number | Theme;
      } | null)
    | ({
        relationTo: 'track-types';
        value: number | TrackType;
      } | null)
    | ({
        relationTo: 'difficulty-levels';
        value: number | DifficultyLevel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs_select".
 */
export interface SongsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  thumbnailPublicId?: T;
  countries?: T;
  languages?: T;
  genres?: T;
  audiences?: T;
  themes?: T;
  difficulty?: T;
  lyrics?:
    | T
    | {
        language?: T;
        text?: T;
        translations?:
          | T
          | {
              language?: T;
              text?: T;
              id?: T;
            };
        id?: T;
      };
  scores?:
    | T
    | {
        pdfPublicId?: T;
        id?: T;
      };
  historyDocuments?:
    | T
    | {
        language?: T;
        pdfPublicId?: T;
        id?: T;
      };
  audioTracks?:
    | T
    | {
        trackType?: T;
        versions?:
          | T
          | {
              versionId?: T;
              name?: T;
              audioPublicId?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "languages_select".
 */
export interface LanguagesSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "genres_select".
 */
export interface GenresSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audiences_select".
 */
export interface AudiencesSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "themes_select".
 */
export interface ThemesSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "track-types_select".
 */
export interface TrackTypesSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "difficulty-levels_select".
 */
export interface DifficultyLevelsSelect<T extends boolean = true> {
  name?: T;
  nameEn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}